### ISSUE TITLE
Doesn't work with Flutter 2.3 for me

### ISSUE THREAD

**Issue by YarosMallorca** [TahaMalas/internet_speed_test#31]
Error:

```
The plugin internet_speed_test uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
lib\main.dart:1
e: C:\Users\siuba\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\internet_speed_test-1.5.0\android\src\main\kotlin\com\tahamalas\internet_speed_test\InternetSpeedTestPlugin.kt: (50, 66): Type mismatch: inferred type is Activity? but Activity was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':internet_speed_test:compileDebugKotlin'.
> Compilation error. See log for more details
```

**Comment by YarosMallorca** [comment]
@TahaMalas Please review this!

Here's a PR I found that fixes it, please approve!
Pull Request https://github.com/TahaMalas/internet_speed_test/pull/28

**Comment by shaz-tech** [comment]
@YarostheLaunchpadder Checkout https://pub.dev/packages/flutter_internet_speed_test
